import * as path from 'node:path';
import { writeFileAtomic } from '../core/fsx.js';
import type { Journey } from './journeys.js';

/**
 * Deterministic Playwright spec generation: one spec file per derived journey,
 * traceable to requirement IDs. QA agents (or CI) execute these with the
 * project's own Playwright install; RIJO never bundles a browser.
 */
export function generatePlaywrightSpecs(journeys: Journey[], outDir: string, baseUrl = 'http://localhost:3000'): string[] {
  const written: string[] = [];
  for (const j of journeys) {
    const file = path.join(outDir, `${j.id.toLowerCase()}.spec.ts`);
    writeFileAtomic(file, renderSpec(j, baseUrl));
    written.push(file);
  }
  return written;
}

function renderSpec(j: Journey, baseUrl: string): string {
  return `// Generated by RIJO — journey ${j.id}
// Requirements: ${j.requirement_ids.join(', ')}
// Persona: ${j.persona}${j.critical ? '\n// CRITICAL journey: failures block production readiness.' : ''}
import { test, expect } from '@playwright/test';

test.describe('${j.id} ${j.name.replace(/'/g, "\\'")}', () => {
  test('completes the journey without console or network errors', async ({ page }) => {
    const consoleErrors: string[] = [];
    const networkErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
    page.on('response', (res) => {
      if (res.status() >= 400) networkErrors.push(\`\${res.request().method()} \${res.url()} → \${res.status()}\`);
    });

    await page.goto('${baseUrl}');
    await expect(page).not.toHaveTitle(/error/i);

    // RIJO-JOURNEY-STEPS: exercise the flow covering ${j.requirement_ids.join(', ')}.
    // The QA agent fills these steps from the requirement acceptance scenarios;
    // this skeleton already enforces the non-negotiable gates below.

    expect(consoleErrors, 'unhandled console errors in critical flow').toEqual([]);
    expect(networkErrors, '4xx/5xx responses in critical flow').toEqual([]);
  });
});
`;
}
