import * as path from 'node:path';
import { writeFileAtomic } from '../core/fsx.js';
import type { Journey, JourneyAction } from './journeys.js';

/**
 * Deterministic Playwright spec generation from STRUCTURED journey actions.
 * A spec always drives the real UI (goto/click/fill/assert) and ties its
 * assertions to requirement IDs; there is no placeholder path — a journey
 * without actions never gets a spec (the gate blocks instead).
 */

export interface GeneratedSpec {
  file: string;
  journeyId: string;
  actionCount: number;
}

export function generatePlaywrightSpecs(
  journeys: Journey[],
  outDir: string,
  baseUrl: string,
  acceptanceById: Record<string, string> = {},
  actionsByJourney: Record<string, JourneyAction[]> = {},
): GeneratedSpec[] {
  const written: GeneratedSpec[] = [];
  for (const j of journeys) {
    const actions = actionsByJourney[j.id];
    if (!actions || actions.length === 0) continue; // no placeholder specs, ever
    const file = path.join(outDir, `${j.id.toLowerCase()}.spec.ts`);
    writeFileAtomic(file, renderSpec(j, baseUrl, acceptanceById, actions));
    written.push({ file, journeyId: j.id, actionCount: actions.length });
  }
  return written;
}

const q = (s: string) => JSON.stringify(s);

function renderAction(a: JourneyAction, baseUrl: string): string {
  switch (a.action) {
    case 'goto':
      return `    await page.goto(${q(new URL(a.path, baseUrl).toString())});`;
    case 'click':
      return `    await page.locator(${q(a.selector)}).click();`;
    case 'fill':
      return `    await page.locator(${q(a.selector)}).fill(${q(a.value)});`;
    case 'press':
      return `    await page.locator(${q(a.selector)}).press(${q(a.key)});`;
    case 'expect_visible':
      return `    await expect(page.locator(${q(a.selector)}), ${q(a.requirement_id ?? 'visibility')}).toBeVisible();`;
    case 'expect_text':
      return `    await expect(page.locator(${q(a.selector)}), ${q(a.requirement_id ?? 'content')}).toContainText(${q(a.text)});`;
    case 'expect_url':
      return `    await expect(page, ${q(a.requirement_id ?? 'navigation')}).toHaveURL(new RegExp(${q(a.pattern)}));`;
  }
}

function renderSpec(
  j: Journey,
  baseUrl: string,
  acceptanceById: Record<string, string>,
  actions: JourneyAction[],
): string {
  const acceptance = j.requirement_ids
    .map((id) => `// ${id}: ${(acceptanceById[id] ?? '').replace(/\n/g, ' ')}`)
    .join('\n');
  const body = actions.map((a) => renderAction(a, baseUrl)).join('\n');
  return `// Generated by RIJO — journey ${j.id} (deterministic codegen from structured actions)
// Requirements: ${j.requirement_ids.join(', ')}
// Persona: ${j.persona}${j.critical ? '\n// CRITICAL journey: failures block production readiness.' : ''}
${acceptance}
import { test, expect } from '@playwright/test';

test.describe('${j.id} ${j.name.replace(/'/g, "\\'")}', () => {
  test('completes the journey without console or network errors', async ({ page }) => {
    const consoleErrors: string[] = [];
    const networkErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
    page.on('response', (res) => {
      if (res.status() >= 400) networkErrors.push(\`\${res.request().method()} \${res.url()} → \${res.status()}\`);
    });

${body}

    expect(consoleErrors, 'unhandled console errors in critical flow').toEqual([]);
    expect(networkErrors, '4xx/5xx responses in critical flow').toEqual([]);
  });
});
`;
}

export interface SpecLintIssue {
  code: string;
  message: string;
}

/** Interaction/assertion markers a real spec must contain. */
const REAL_ACTION = /page\.locator\(|page\.goto\(|toHaveURL\(|toContainText\(/;
const PLACEHOLDER = /TODO|TBD|FIXME|placeholder|Drive the UI to satisfy/i;
const BODY_VISIBLE_ONLY = /locator\((['"`])body\1\)/;

/**
 * Deterministic spec lint: rejects placeholder-only specs — a spec with no
 * real interaction, a body-visible-only assertion, placeholder comments or no
 * requirement linkage never counts as journey coverage.
 */
export function lintPlaywrightSpec(content: string, journey: Journey): SpecLintIssue[] {
  const issues: SpecLintIssue[] = [];
  if (PLACEHOLDER.test(content)) {
    issues.push({ code: 'SPEC_PLACEHOLDER', message: 'spec contains placeholder markers (TODO/TBD/FIXME/placeholder)' });
  }
  const meaningful = content
    .split('\n')
    .filter((l) => REAL_ACTION.test(l) && !BODY_VISIBLE_ONLY.test(l));
  if (meaningful.length === 0) {
    issues.push({ code: 'SPEC_NO_REAL_ACTION', message: 'spec drives no real UI action (body-visible-only or empty)' });
  }
  const linked = journey.requirement_ids.some((id) => content.includes(id));
  if (!linked) {
    issues.push({ code: 'SPEC_NO_REQUIREMENT_LINK', message: `spec references none of the journey requirements (${journey.requirement_ids.join(', ')})` });
  }
  return issues;
}
